# Base URL
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MDZhMmE1My1hZjM1LTQwODUtODRiNC00MjQ0ODgxODg1YjEiLCJpYXQiOjE3NTU4MTEwMDMsImV4cCI6MTc1NjQxNTgwM30.R6e1aqWO2d3YMBIPIv9ezMobeGdA1auaZ2CtJOtaa5Y
###

# create account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "rodrigo@acme.com",
  "name": "Rodrigo Acme",
  "password": "123123"
}

###

# authenticate with password
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "rodrigo@acme.com",
  "password": "123123"
}

###

# get profile
GET {{baseUrl}}/profile
Authorization: Bearer {{ token }}
