# Base URL
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MDZhMmE1My1hZjM1LTQwODUtODRiNC00MjQ0ODgxODg1YjEiLCJpYXQiOjE3NTU4MTM0ODQsImV4cCI6MTc1NjQxODI4NH0.fvE8bZ-vtD_Yw2jOjmeWLZ5Z6Atyco2YiEFbhf60d-w
###

# create account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "rodrigo@senna.com",
  "name": "Rodrigo Senna",
  "password": "123123"
}

###

# authenticate with password
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "rodrigo@acme.com",
  "password": "123123"
}

###

# get profile
GET {{baseUrl}}/profile
Authorization: Bearer {{ token }}
