# Base URL
@baseUrl = http://localhost:3333

###

# create account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "rodrigo@acme.com",
  "name": "Rodrigo Acme",
  "password": "123123"
}

###

# authenticate with password
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "rodrigo@acme.com",
  "password": "123123"
}